version: "3.8"
services:
  app:
    build: .
    container_name: my-social-api
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: my-social-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-my_social_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pgdata:
